# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa1e43777e8ba938d9c0a3403365a0c553fb93cf26af26fbfce6841e5ffb60aa550a0edf46a0eca5b47e879b5b4bd3c681946f0c74a9d66dc51c44db849653dd

test:
  secret_key_base: 1bb7872c37eec25dcf360f45a088065eeaf504da9a0d42c06de9fa22640e568be0d9cf3ec966fe3be90bb388be47ca26097822447f4512cc5958781d0a8fda36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>